### PR TITLE
Fixed the errors and build is successful 

### PR DESCRIPTION
**Pull request by asterisk-ragavan**
used Python code to download the OTA.
added the python execution to the workflow.
build magisk module has come env bug and fixed it and the build is fine.

### CODE REVIEW

**Comment by asterisk-ragavan** [comment]
check and review the code

**Comment by 0x11DFE** [comment]
> check and review the code

Is it necessary to rewrite the bash download script into python? I believe it should and could be a simple bash project.
None the less if you want me to allow the changes you must rewrite it fully into python.
Else keep the fixed GitHub Actions and use bash.

Also you added imjtool applet which is unnecessary since the requirements and util functions are supposed to download and fetch the latest version of that applet.

If you believe the schedules were broken because of the download bash script, it is not.
The issue could have been on my utils bash functions.

**Comment by 0x11DFE** [comment]
Check the latest changes.

**Comment by asterisk-ragavan** [comment]
the bash script is throwing errors in the GitHub workflow, I tried the same script in my local WSL and I didn't get any error.

the website where the imjtool hisas hosted had lost the SHL certificate, and the request to the website failed due to it, however we are not using imjtool for the latest versions of Android, so I added it like a soft fix to suppress the requirement error.

**Comment by 0x11DFE** [comment]
> the bash script is throwing errors in the GitHub workflow, I tried the same script in my local WSL and I didn't get any error.
> 
> the website where the imjtool hisas hosted had lost the SHL certificate, and the request to the website failed due to it, however we are not using imjtool for the latest versions of Android, so I added it like a soft fix to suppress the requirement error.

True we don't need imjtool, only if i didn't plan to make it work across other device brands.
I believe we should extend it to support other phone brands.

**Pull request closed without merging**
